# Generated by Django 4.1.7 on 2023-02-22 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, null=True, verbose_name='Nome Completo')),
                ('observation', models.CharField(max_length=255, verbose_name='Observação')),
                ('special', models.CharField(choices=[(0, 'Cirurgião plástico'), (1, 'Psiquiatra'), (2, 'Pediatra'), (3, 'Neurologista'), (4, 'Oncologista'), (5, 'Ginecologista'), (6, 'Homeopata'), (7, 'Alergista'), (8, 'Nutricionista'), (9, 'Pneumologista'), (10, 'Dermatologista'), (11, 'Geriatra'), (12, 'Neurocirurgião'), (13, 'Angiologista'), (14, 'Urologista'), (15, 'Psicólogo'), (16, 'Cardiologista'), (17, 'Acupunturista'), (18, 'Neuropsicólogo'), (19, 'RPG'), (20, 'Ortopedista e Traumatologista')], max_length=1, null=True, verbose_name='Especialidade médica')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, null=True, verbose_name='Nome Completo')),
                ('observation', models.CharField(max_length=255, verbose_name='Observação')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True, verbose_name='Data e Hora')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.doctor', verbose_name='Doutor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.patient', verbose_name='Paciente')),
            ],
            options={
                'unique_together': {('doctor', 'patient', 'date')},
            },
        ),
    ]
