# Generated by Django 4.1.7 on 2023-03-01 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(error_messages={'required': 'Por favor insira um nome valido'}, max_length=255, verbose_name='Nome Completo')),
                ('observation', models.CharField(blank=True, default='', max_length=255, verbose_name='Observação')),
                ('special', models.CharField(choices=[('cp', 'Cirurgião plástico'), ('ps', 'Psiquiatra'), ('pd', 'Pediatra'), ('ne', 'Neurologista'), ('on', 'Oncologista'), ('gi', 'Ginecologista'), ('ho', 'Homeopata'), ('al', 'Alergista'), ('nu', 'Nutricionista'), ('pn', 'Pneumologista'), ('de', 'Dermatologista'), ('ge', 'Geriatra'), ('nr', 'Neurocirurgião'), ('an', 'Angiologista'), ('ur', 'Urologista'), ('pi', 'Psicólogo'), ('ca', 'Cardiologista'), ('ac', 'Acupunturista'), ('nu', 'Neuropsicólogo'), ('rp', 'RPG'), ('ot', 'Ortopedista e Traumatologista')], max_length=50, verbose_name='Especialidade médica')),
                ('crm', models.IntegerField(unique=True, verbose_name='Crm do médico')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(error_messages={'required': 'Por favor insira um nome valido'}, max_length=255, verbose_name='Nome Completo')),
                ('observation', models.CharField(blank=True, default='', max_length=255, verbose_name='Observação')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Data e Hora')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.doctor', verbose_name='Doutor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient', verbose_name='Paciente')),
            ],
            options={
                'unique_together': {('doctor', 'patient', 'date')},
            },
        ),
    ]
